version: '3'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5432:5432"

  cleaning-service:
    build: ./
    restart: always
    container_name: service
    command:
      - sh
      - '-c'
      - 'sleep 5 && npx prisma db push && node index.js'
    depends_on:
      - postgres
    ports:
      - "3001:3001"